#http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  datasource:
    driver-class-name: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/calendar_feed"
    username: "dsd"
    password: "password"

#  mvc:
#    view:
#      prefix: "/webapp/view"
#      suffix: ".jsp"

  jpa:
    hibernate:
      ddl-auto: "create"
    show-sql: true